name: GO-CYB Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    runs-on: ubuntu-latest
    environment: testing
    env:
      SOCKET_SERVER_HOST: 127.0.0.1
      SOCKET_SERVER_PORT: 2022
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Run Go-CYB Tests
      run: bash test.sh
