name: GO-CYB Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    runs-on: ubuntu-latest
    environment: testing
    env:
      SOCKET_SERVER_HOST: secrets.SOCKET_SERVER_HOST
      SOCKET_SERVER_PORT: secrets.SOCKET_SERVER_PORT
      DB_DRIVER: secrets.DB_DRIVER
      DB_HOST: secrets.DB_HOST
      DB_PORT: secrets.DB_PORT
      DB_USERNAME: secrets.DB_USERNAME
      DB_PASSWORD: secrets.DB_PASSWORD
      DB_DATABASE: secrets.DB_DATABASE
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Run Go-CYB Tests
      run: bash test.sh
